name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Planejamento1
      id: planejamento1
      uses: education/autograding-io-grader@v1
      with:
        test-name: Planejamento1
        command: make main
        input: "1\r\n1"
        expected-output: '2'
        comparison-method: exact
        timeout: 5
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        PLANEJAMENTO1_RESULTS: "${{steps.planejamento1.outputs.result}}"
      with:
        runners: planejamento1
